#!/bin/sh -e

# shellcheck disable=SC3024
# shellcheck disable=SC3030
# shellcheck disable=SC1078
DIR=$(dirname "$(readlink -f -- "$0")")
C_ERROR="\033[0;31m"
C_WARN="\033[0;33m"
C_VERBOSE="\033[0;32m"
C_NOTICE="\033[0;34m"
C_NONE="\033[0m"
set_usage() {
  USAGE="""Usage: ${CMD:=${0##*/}} ${1:-"[bootstrap|up|down|build|help]"} [APPS...|(-a|--all)] [(-v|--verbose)] [(-d|--dry-run)] [(-h|--help)]
  APPS:
    The apps to run this command on.
    
  Options:
    -a|--all - apply to all apps
    -v|--verbose - output additional info to stderr; pass multiple times for greater verbosity
    -d|--dry-run - preview the commends to be run, but do not execute them
    -h|--help - display help text
    ${2}
  
  Examples:
    ${C_VERBOSE}Bootstrap the project${C_NONE}
    ./castle bootstrap
    
    ${C_VERBOSE}Build baseline required images, plus mastodon and sharkey${C_NONE}
    ./castle build mastodon sharkey --required
    
    ${C_VERBOSE}Run mastodon and letterbook${C_NONE}
    ./castle up mastodon letterbook"""
}; set_usage;
set_help() {
  HELP="""Sandcastles - ${C_VERBOSE}${1:-"federation sandbox"}${C_NONE}
  ${2:-"""Easily and quickly set up a federation sandbox, for testing against
  production-like configurations of multiple fediverse backends."""}
  """
}; set_help;
exit2 () { printf >&2 "%s:  %s: '%s'\n%b\n" "$CMD" "$1" "$2" "$USAGE"; exit 2; }
exit_runtime () { 
  printf >&2 "Sandcastles require a container runtime\nYou must install either podman (and podman-compose) or docker"; 
  exit 3;
}
exit_err() {
  printf >&2 "${C_ERROR}%s Error!${C_NONE}\n%b\n" "$1" "⤷ $2"; exit 4
}
exit_usage() { printf "%b\n" "$USAGE"; exit 0; }
exit_help() { printf "%b\n%b\n" "$HELP" "$USAGE"; exit 0; }
check () { { [ "$1" != "$EOL" ] && [ "$1" != '--' ]; } || exit2 "missing argument" "$2"; }  # avoid infinite loop
verbose () {
  if [ "$opt_verbose" -gt 0 ]; then
    debug=$1; shift
    printf "${C_VERBOSE}%s${C_NONE}\n%s\n" "$debug"  "⤷ $(printf "%s " "$@")" >&2
  fi
}
verbose2 () {
  if [ $opt_verbose -gt 1 ]; then
    verbose "$@"
  fi
}

# run commands with support for verbose output and dry-runs
run() {
  debug=$1; shift
  cmd_args=("$@")
  if [ "$opt_dryrun" = "true" ]; then
    printf "${C_NOTICE}(dry-run) ${C_VERBOSE}$debug${C_NONE}\n%s\n" "⤷ $(printf "%s %s" "${cmd_args[*]}" "${arg_pass[*]}")" >&2
    return
  fi
  if [ "$opt_verbose" -gt 0 ]; then
    verbose "$debug" "${cmd_args[*]}"
  fi
  if [ ${#arg_pass[@]} -gt 0 ]; then
    verbose "passthrough" "${#arg_pass[@]}"
    "${cmd_args[@]}" "${arg_pass[*]}"
  else
    "${cmd_args[@]}"
  fi
  code=$?
  if [ $code = 0 ]; then
    return
  fi
  exit $code
}

# parse action
case "$1" in
  # handle help cases
  -h | --help | help ) exit_help;;
  '' ) exit_usage;;
  bootstrap ) opt_action=$1; shift
    set_help "$opt_action" "perform first time setup"
    set_usage "$opt_action"
    ;; 
  up ) opt_action=$1; shift
    set_help "$opt_action" "run the selected apps"
    set_usage "$opt_action"
    ;;
  down ) opt_action=$1; shift
    set_help "$opt_action" "shut down the selected apps"
    set_usage "$opt_action"
    ;;
  build ) opt_action=$1; shift
    set_help "$opt_action" "Build container images with trust for your Sandcastle private CA"
    set_usage "$opt_action" "-r|--required - build required container images not associated with an individual app"
    ;;
  new ) opt_action=$1; shift
    set_help "$opt_action" "Scaffold up required files to add new apps to the Sandcastle. New app names should follow the command"
    ;;
  * ) exit2 "invalid command" "$opt_action";;
esac

# parse remaining command-line options
set -- "$@" "${EOL:=$(printf '\1\3\3\7')}"  # end-of-list marker
opt_apps=()
opt_verbose=0
arg_pass=()
while [ "$1" != "$EOL" ]; do
  opt="$1"; shift
  case "$opt" in

    # defined options
    -a | --all      ) opt_all=true;;
    -h | --help     ) exit_help;;
    -r | --required ) opt_required=true;;
    -v | --verbose  ) opt_verbose=$((opt_verbose + 1));;
    -d | --dry-run  ) opt_dryrun=true;;

    # process special cases
    --) while [ "$1" != "$EOL" ]; do set -- "$@" "$1"; arg_pass+=("$1"); shift; done;;   # parse remaining as passthrough
    --[!=]*=*) set -- "${opt%%=*}" "${opt#*=}" "$@";;                                    # "--opt=arg"  ->  "--opt" "arg"
    -[A-Za-z0-9] | -*[!A-Za-z0-9]*) exit2 "invalid option" "$opt";;                      # anything invalid like '-*'
    -?*) other="${opt#-?}"; set -- "${opt%$other}" "-${other}" "$@";;                    # "-abc"  ->  "-a" "-bc"
    *) opt_apps+=("$opt");;                                                              # positional, rotate to the end
  esac
done; shift

if (command -v podman >/dev/null 2>&1) && (command -v podman-compose >/dev/null 2>&1);  then
  env_runtime="podman"
elif command -v docker >/dev/null 2>&1;  then
  env_runtime="docker"
else
  exit_runtime
fi

verbose2 "parsed options" """DIR = '$DIR'
  action = '$opt_action'
  arg_pass = ${arg_pass[*]}
  apps = ${opt_apps[*]}
  --all = $opt_all
  --required = $opt_required
  --verbose = $opt_verbose
  --dry-run = $opt_dryrun
  runtime = '$env_runtime'"""

# Zhu Li, do the thing!
case $opt_action in
  up )
    compose_files=("-f" "$DIR/docker-compose.yml")
    if [ "$opt_all" = "true" ]; then
      all_files=$(find "$DIR" -type f -name "*.compose.yml")
      for n in ${all_files[*]}; do compose_files+=("-f" "$n"); done 
    else
      for n in ${opt_apps[*]}; do compose_files+=("-f" "$n.compose.yml"); done
    fi
    cmd_args=("$env_runtime" "compose" "${compose_files[@]}" "up" "-d")
    if [ "$env_runtime" = "podman" ]; then
      CONTAINERS_CONF_OVERRIDE="$DIR/volumes/containers.conf"
      export CONTAINERS_CONF_OVERRIDE
    fi
    run "compose up" "${cmd_args[@]}"
  ;;

  build )
    docker_files=()
    if [ "$opt_all" = "true" ]; then
      verbose "find all Dockerfiles"
      docker_files+=$(find "$DIR" -type f -name "*.Dockerfile")
    elif [ "$opt_required" = "true" ]; then
      verbose "find Dockerfiles" "--required"
      docker_files+=("$DIR/traefik.Dockerfile" "$DIR/network-tools.Dockerfile")
    fi
    if [ "$opt_all" != "true" ]; then
      for n in ${opt_apps[*]}; do
        verbose "find Dockerfiles" "$n"
        found=$(find "$DIR" -type f -name "$n*.Dockerfile")
        docker_files+=("$found")
      done
    fi
    verbose "found" ${docker_files[*]}
    
#    tags() is an array of "tuples" which don't exist in sh scripts as far as I know.
#    so, it's actually a regular array, but with paired elements.
#    Like ("x.Dockerfile" "tag/x:latest" "y.Dockerfile" "tag/y:latest")...
    tags=()
    for n in ${docker_files[*]}; do
      tags+=("$n" "localhost/sandcastles/$(basename ${n//.Dockerfile})");
    done
    
    i=0
    while [ "$i" -lt ${#tags[@]} ]; do 
      cmd_args=("$env_runtime" "build" "$DIR" "-f" "${tags[i]}" "-t" "${tags[i+1]}:latest")
      if [ $env_runtime = "podman" ]; then
        cmd_args+=("--format" "docker")
      fi
      run "build ${tags[i+1]}" "${cmd_args[@]}"
      i=$((i+2))
    done
  ;;

  down )
    compose_files=()
    if [ "$opt_all" = "true" ]; then
      compose_files+=("-f" "$DIR/docker-compose.yml")
      all_files=$(find "$DIR" -type f -name "*.compose.yml")
      for n in ${all_files[*]}; do compose_files+=("-f" "$n"); done 
    else
      for n in ${opt_apps[*]}; do compose_files+=("-f" "$n.compose.yml"); done
    fi
    cmd_args=("$env_runtime" "compose" "${compose_files[@]}" "down")
    run "compose down" "${cmd_args[@]}"
  ;;

  bootstrap )
    if [ -d "$DIR/volumes/root-ca/secrets" ]; then
        exit_err "$opt_action" """Refusing to overwrite data in ${C_WARN}$DIR/volumes/root-ca/${C_NONE}
  This project has already been bootstrapped. You must remove the secrets stored in
  ${C_WARN}$DIR/volumes/root-ca/${C_NONE} before you can bootstrap again.
  Those secrets cannot be recovered later! Make a copy of them, or revoke trust in them before they are deleted."""
    fi

    run "create sandcastles internal CA" "$env_runtime" "compose" "-f" "$DIR/bootstrap.yml" "up" "-d"
    container_id=$(run "get container id" "$env_runtime" "compose" "-f" "bootstrap.yml" "ps" "-q")
    container_id=${container_id:-"dry-run_container"}
    run "wait for container" sleep 1
    run "extract private key for sandcastles internal CA" \
      "$env_runtime" "cp" "$container_id:/home/step/templates" "$DIR/volumes/root-ca/"
    run "..." "$env_runtime" "cp" "$container_id:/home/step/secrets" "$DIR/volumes/root-ca/"
    run "..." "$env_runtime" "cp" "$container_id:/home/step/db" "$DIR/volumes/root-ca/"
    run "..." "$env_runtime" "cp" "$container_id:/home/step/certs" "$DIR/volumes/root-ca/"
    run "..." "$env_runtime" "compose" "-f" "bootstrap.yml" "down"
    
    run "configure access to sandcastles internal CA" mkdir "-p" "$DIR/volumes/root-ca/config"
    run "..." "cp" "$DIR/volumes/ca.json" "$DIR/volumes/root-ca/config/ca.json"
    run "..." "find" "$DIR/volumes/root-ca" "-type" "d" "-exec" "chmod" "755" "{}" "+"
    run "..." "find" "$DIR/volumes/root-ca" "-type" "f" "-exec" "chmod" "644" "{}" "+"
    
    run "collect info about the runtime environment" \
      printf "%s\n" "DOCKER_PATH=${DOCKER_HOST//"unix://"}" > "$DIR/.env"
    run "..." printf "%s\n" """[containers]
base_hosts_file = \"$DIR/volumes/hosts\" """ > "$DIR/volumes/containers.conf"
  ;;

  new )
    compose_template=$(cat "$DIR/templates/compose.yml")
    docker_template=$(cat "$DIR/templates/Dockerfile")
    for n in ${opt_apps[*]}; do
      compose_file=${compose_template//"{{app_name}}"/$n}
      docker_file=${docker_template//"{{app_name}}"/$n}
      run "generate compose template for $n" printf "%s\n" "$compose_file" > "$DIR/$n.compose.yml"
      run "generate Dockerfile template for $n" printf "%s\n" "$docker_file" > "$DIR/$n.Dockerfile"
    done
  ;;
esac
