# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0
# Configuration adapted from
# https://github.com/bitnami/containers/blob/main/bitnami/mastodon/docker-compose.yml

# must be used as an overlay for the main docker-compose file. Ex
# docker-compose -f docker-compose.yml -f mastodon.castle.yml up

# defaults
# admin: user@bitnami.org
# password: bitnami1

services:
  mastodon:
    labels:
      - traefik.http.routers.mastodon.rule=Host(`mastodon.castle`)
      - traefik.http.routers.mastodon.tls=true
      - traefik.http.routers.mastodon.tls.certresolver=smallstep
      - traefik.http.services.mastodon-sandcastles.loadBalancer.healthCheck.path=/health
      - traefik.port=3000
      - traefik.enable=true
      - traefik.docker.network=fediverse
    depends_on:
      - mastodon_db
      - mastodon_redis
    image: localhost/mastodon-sandcastle
    build:
      dockerfile: mastodon.Dockerfile
      tags:
        - localhost/mastodon-sandcastle
    volumes:
      - mastodon_data_web
    networks:
      - mastodon
      - default
    environment: &mastodon_env
      - MASTODON_DATABASE_HOST=mastodon_db
      - MASTODON_REDIS_HOST=mastodon_redis
      - ALLOW_EMPTY_PASSWORD=yes
      - MASTODON_MODE=web
      - MASTODON_DATABASE_PASSWORD=bitnami1
      - LOCAL_DOMAIN=mastodon.castle
      - MASTODON_WEB_DOMAIN=mastodon.castle
      - MASTODON_HTTPS_ENABLED=true
      - MASTODON_ELASTICSEARCH_ENABLEd=false
      - ALLOWED_PRIVATE_ADDRESSES=127.0.0.1,172.0.0.0/8,192.0.0.0/8
      - RAILS_ENV=development
      # - RAILS_ENV=production
    restart: unless-stopped
  
  mastodon-streaming:
    depends_on:
      - mastodon
    image: localhost/mastodon-sandcastle
    build:
      dockerfile: mastodon.Dockerfile
      tags:
        - localhost/mastodon-sandcastle
    networks:
      - mastodon
    environment: *mastodon_env
    restart: unless-stopped
  
  mastodon-sidekiq:
    depends_on:
      - mastodon
    image: localhost/mastodon-sandcastle
    build:
      dockerfile: mastodon.Dockerfile
      tags:
        - localhost/mastodon-sandcastle
    volumes:
      - mastodon_data_web
    networks:
      - mastodon
      - default
    environment: *mastodon_env
    restart: unless-stopped

  mastodon_db:
    image: docker.io/bitnami/postgresql:16
    networks:
      - mastodon
    volumes:
      - 'mastodon_data_db:/bitnami/postgresql'
    environment:
      - POSTGRESQL_DATABASE=bitnami_mastodon
      - POSTGRESQL_USERNAME=bn_mastodon
      - POSTGRESQL_PASSWORD=bitnami1
    restart: unless-stopped
  
  mastodon_redis:
    image: docker.io/redis:7.4-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mastodon_data_redis:/data'
    networks:
      - mastodon
    restart: 'no'

  # Configure docker's internal DNS
  # Traefik will provide SSL termination and proxy back to mastodon
  proxy:
    networks:
      default:
        aliases:
          - mastodon.castle

volumes:
  mastodon_data_db:
    driver: local
  mastodon_data_redis:
    driver: local
  mastodon_data_web:
    driver: local

networks:
  mastodon:
  default:
  fediverse:
