# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0
# Configuration adapted from
# https://github.com/bitnami/containers/blob/main/bitnami/mastodon/docker-compose.yml

# must be used as an overlay for the main docker-compose file. Ex
# docker-compose -f docker-compose.yml -f mastodon.castle.yml up

# defaults
# admin: user@bitnami.org
# password: bitnami1

services:
  mastodon:
    labels:
      - traefik.http.routers.mastodon.rule=Host(`mastodon.castle`)
      - traefik.http.routers.mastodon.tls=true
      - traefik.http.routers.mastodon.tls.certresolver=smallstep
      - traefik.http.services.mastodon-sandcastles.loadBalancer.healthCheck.path=/health
      - traefik.port=3000
      - traefik.enable=true
      - traefik.docker.network=fediverse
    depends_on:
      - mastodon_db
      - mastodon_redis
    build:
      dockerfile: ./mastodon.Dockerfile
      tags:
        - localhost/mastodon-sandcastle:latest
    volumes:
      - 'mastodon_data_web:/bitnami/mastodon'
    ports:
      - '2970:3000'
    networks:
      - mastodon
      - default
    environment: &mastodon_env
      MASTODON_DATABASE_HOST: mastodon_db
      MASTODON_REDIS_HOST: mastodon_redis
      ALLOW_EMPTY_PASSWORD: yes
      MASTODON_MODE: web
      MASTODON_DATABASE_PASSWORD: password
      MASTODON_DATABASE_USERNAME: mastodon
      MASTODON_DATABASE_NAME: mastodon
      LOCAL_DOMAIN: mastodon.castle
      MASTODON_WEB_DOMAIN: mastodon.castle
      MASTODON_HTTPS_ENABLED: true
      ALLOWED_PRIVATE_ADDRESSES: 127.0.0.1,172.0.0.0/8,192.0.0.0/8
      RAILS_ENV: development
    restart: unless-stopped
  
  mastodon-streaming:
    depends_on:
      - mastodon
    build:
      dockerfile: mastodon.Dockerfile
      tags:
        - localhost/mastodon-sandcastle:latest
    networks:
      - mastodon
    environment: *mastodon_env
    restart: unless-stopped
  
  mastodon-sidekiq:
    depends_on:
      - mastodon
    build:
      dockerfile: mastodon.Dockerfile
      tags:
        - localhost/mastodon-sandcastle:latest
    volumes:
      - 'mastodon_data_web:/bitnami/mastodon'
    networks:
      - mastodon
      - default
    environment: *mastodon_env
    restart: unless-stopped

  mastodon_db:
    image: docker.io/postgres:16-alpine
    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_DB: mastodon
      POSTGRES_PASSWORD: password
      POSTGRES_USER: mastodon
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    volumes:
      - mastodon_data_db:/var/lib/postgresql/data
      - ./volumes/postgresql.conf:/etc/postgresql/postgresql.conf:z

  mastodon_redis:
    image: docker.io/redis:7.4-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mastodon_data_redis:/data'
    networks:
      - mastodon
    restart: 'no'

  # Configure docker's internal DNS
  # Traefik will provide SSL termination and proxy back to mastodon
  proxy:
    networks:
      default:
        aliases:
          - mastodon.castle

volumes:
  mastodon_data_db:
    driver: local
  mastodon_data_redis:
    driver: local
  mastodon_data_web:
    driver: local

networks:
  mastodon:
  default:
