[http.middlewares.simpleAuth.basicAuth]
  users = [
    # username: sandcastles
    # password: admin
    "sandcastles:$apr1$Xe1bQOFU$OQ.6qf4QCcRk5E8mQ.yt4."
  ]

[http.routers.api]
  rule = "Host(`dashboard.castle`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "smallstep"
