[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
    to = "websecure"
    scheme = "https"
  [entryPoints.websecure]
    address = ":443"
    
[api]
  dashboard = true

[certificatesResolvers.smallstep.acme]
  caServer = "https://root-ca.castle:9000/acme/acme/directory"
  storage = "acme.json"
  [certificatesResolvers.smallstep.acme.httpChallenge]
    entryPoint = "web"

[providers.docker]
  watch = true
  network = "traefik"
  endpoint = "tcp://dockerproxy:2375"
  exposedByDefault = false

[providers.file]
  filename = "/etc/traefik/traefik_dynamic.toml"
