[http.middlewares.simpleAuth.basicAuth]
  users = [
    # username: sandcastles
    # password: admin
    "sandcastles:$apr1$Xe1bQOFU$OQ.6qf4QCcRk5E8mQ.yt4."
  ]

[http.routers.api]
  rule = "Host(`dashboard.castle`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "smallstep"

[http.routers.dockerhost]
    rule = "Host(`host.castle`)"
    entrypoints = ["websecure", "web"]
    service = "dockerhost"
    [http.routers.dockerhost.tls]
      certResolver = "smallstep"

[http.services.dockerhost]
    [http.services.dockerhost.loadBalancer.healthCheck]
      path = "/swagger/v1/swagger.json"
      port = 5127
    [[http.services.dockerhost.loadBalancer.servers]]
      url = "http://host.docker.internal:5127"